site_name: Phoenix3 Project
repo_url: https://github.com/Blackksoulls/phoenix3
pages:
 - Menu: index.md
 - Rack / moteur:
   - Documentation rack: docs/rack.md
   - Documentation moteur: docs/moteur.md
 - Application android:
   - Recherche application: docs/app.md
   - Fonctionnement application: docs/appfunc.md

theme: readthedocs
